### PR TITLE
Revert "Remove private jobs"

### LINKED ISSUE #995: [BUG] Web: RabbitMQ Update sabatoges `acks_late`
**Describe the bug**
Jobs longer than 30 minutes are failing after rabbitMq made a behavior change.  It's not clear why this just started, perhaps our Rabbit node was updated by AWS without them telling us.

**To Reproduce**
Using version > 3.8.15, try to run a job for longer than 30 minutes.

**Related data**
```
[2021-10-14 06:31:46,642: INFO/MainProcess] Received task: dive_tasks.tasks.run_pipeline[a9bc43bf-47d3-47a7-9eed-b05d9c5c40a2]  
[2021-10-14 07:01:46,699: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '')
```

https://groups.google.com/g/celery-users/c/5dPhSfF5APQ

**Expected behavior**
Jobs should be allowed to run for longer than 30 min.

### PR DESCRIPTION
**Pull request by subdavis**
Reverts Kitware/dive#997

fixes #995

### CODE REVIEW

**Comment by subdavis** [comment]
now that the nightly deploy has passed, this is safe to merge.

**Comment by BryonLewis** [comment]
going to want to add this back in as well I guess?
https://github.com/Kitware/dive/commit/38bec374edff2a92282442b12466f3ba69935afe#diff-d70fd7335387aa8265415f75bcaf6fd8498f332c03cdb889c90302e02c034790

**Comment by subdavis** [comment]
Do you mean the google cloud docs?  Those were never removed.

All that now lives in https://kitware.github.io/dive/Deployment-Provision/ Scenario 3.

Sorry if I misinterpreted.

**Comment by BryonLewis** [comment]
> Do you mean the google cloud docs? Those were never removed.
> 
> All that now lives in https://kitware.github.io/dive/Deployment-Provision/ Scenario 3.
> 
> Sorry if I misinterpreted.

That's good to know thanks.   The link on the Jobs page may want to be modified to point there then.

**Comment by subdavis** [comment]
Updated all broken links related to the gh pages site.

**Review by BryonLewis — APPROVED** [review]

**Pull request merged**
