### PR TITLE
Export detections above threshold by default

### LINKED ISSUE #696: [FEATURE] Desktop: export detections above threshold by default not all detections
Possibly can be debated but I think that the box should be checked for export above threshold by default not vica versa

### PR DESCRIPTION
**Pull request by f4str**
fixes #696 

Export above threshold checkbox enabled by default on both desktop and web. Also changed the variable name to something more specific since there are two export option checkboxes now.

### CODE REVIEW

**Comment by BryonLewis** [comment]
This seems to work very well as intended.  I did notice an inconsistency in the UI and I'm wondering if that should be resolved.  In both the desktop and web if you open export before adjusting the confidence filter you don't get an option to filter below the current confidence level (because the metadata filter level isn't set yet).  This is okay because it exports everything.  The problem comes with our default value 0.10.  If you open a dataset with items that are below 0.10 and then export without adjusting the slider you are exporting more items than you see in the annotation screen.
image
If I was to export this It would get the extra track at 0.5 confidence level and export it.

So the question remains if we should default the confidence filter metadata value to 0.10 on load or should we default the UI to 0.0 when starting off?

**Comment by f4str** [comment]
The bug with the metadata should be fixed now. When a new dataset is uploaded, it displays the checkboxes correctly.

**Comment by BryonLewis** [comment]
> The bug with the metadata should be fixed now. When a new dataset is uploaded, it displays the checkboxes correctly.

Awesome, I think something similar needs to be done on desktop as well.  If I remember correctly it had the same behavior in that the metadata value for the confidence didn't set until the user initially drags the confidence slider?  I'll double check later though.

**Comment by f4str** [comment]
Made the same change for desktop. Should be fixed now.

**Review by BryonLewis — CHANGES_REQUESTED** [review]
In the testing of uploading and checking the metadata it works perfectly for desktop/web.  Sets the default value and exports the proper data.

This may seem way too picky so feel free to push back.  Instance of having previously existing uploaded data that didn't have a confidence filter set.  Then a user clones that data without confidence value being set it won't have a default value so you would run into the same problem.  It seems extraordinarily rare, but looking through our Training Data collections on the server there are some datasets that don't have a meta value set. https://viame.kitware.com/girder#collection/5e4c256ca0fc86aa03120c34/folder/6074b989244544940f771ff0
Should just add an additional check to the cloning to see if cloned from folder doesn't have `ConfidenceFiltersMarker` and set it if it doesn't exist.

**Comment by f4str** [comment]
@BryonLewis this should take care of that edge case. When cloning a dataset that doesn't have the `ConfidenceFilterMarker` metadata set, manually set it to 0.1 on the clone. The original dataset without the metadata will be left untouched.

**Review by BryonLewis — APPROVED** [review]
Looks good.

**Pull request merged**
