### PR TITLE
Web Stereoscopic Support

### PR DESCRIPTION
**Pull request by BryonLewis**
Started working on a web version of the stereoscopic and that is going to require some changes to the upload of data.  At the very least we needed a way to add the multicam dialogs to the web version.

Tasks Completed:

- Converted openFromDisk to be used in both web and Desktop.
-  Moved types for import files to dive-common as well so they can be used while importing data for file filtering
- Created a openFromDisk in `viame.service.ts`   Added filetype filtering to the open dialog that should work properly.
- Moved a bunch of shared datatypes and components to `dive-common` from the `desktop` (mostly that deal with multiCam).  Stuff like the constants for file types, the MultiCamInputArgs, and a shared sense of `openFromDisk` so that the shared multicam args can be used across both.
- Removed girder dropzone to replace it with the import buttons
- Moved ImportButton and ImportMultiCamDialog to dive-common where both web and desktop can use their functionality.
- Updated pendingUpload to display the media files, annotation file and meta file individually as well as allow the user to edit it.  Metadata files are currently hidden until they are supported as well as multi-cam/stereo
- Refactored the mixin stuff into  `GirderUpload.vue` component into a subset of Upload so I could switch `Upload.vue` into a typescript component.  `Upload.vue`  manages file opening and organization as well as display of progress, the `GirderUpload.vue` handles all mixin aspects of uploading to Girder.

### CODE REVIEW

**Comment by BryonLewis** [comment]
@subdavis - just looking for initial impresses and if I am on the proper track.  It's a prerequisite to get stereo data uploaded into web to be able to use it anyway.

https://user-images.githubusercontent.com/61746913/116925887-c6909c00-ac27-11eb-986b-d1997ac4b295.mp4

**Comment by subdavis** [comment]
I drew this while we were talking earlier.  I'll read through and watch the video when my meetings are over.  Thanks for the write-up.

IMG_0371

**Comment by BryonLewis** [comment]
I like that mock-up and will probably change stuff to look a bit more like that.

**Comment by subdavis** [comment]
You don't need to change anything yet.  We can make a second pass later if what you have now is a good first pass.

**Review by subdavis — APPROVED** [review]
Looks great!

:ship: :it:

**Pull request merged**
