### PR TITLE
Add girder search

### PR DESCRIPTION
**Pull request by subdavis**
Add the boilerplate search bar.

Mentioned in #687 

Screenshot from 2021-04-07 21-15-04

### CODE REVIEW

**Comment by BryonLewis** [comment]
https://github.com/girder/girder_web_components/blob/master/src/components/Search.vue#L182 ??
Is there a reason why this is locked to the light theme?  All the sub components theme correctly it's just the text-field itself which is locked to the light theme.
image

**Comment by subdavis** [comment]
No, there is no good reason for that.

**Comment by subdavis** [comment]
Updated to dark search

**Review by BryonLewis — CHANGES_REQUESTED** [review]
uncaught `NavigationDuplicated` router errors  if attempting to use search to go to your current location.

**Comment by subdavis** [comment]
That last comment lead me to the discovery that forward/back browser buttons didn't work, so I went ahead and fixed that too.

**Review by BryonLewis — APPROVED** [review]

**Pull request merged**
