### PR TITLE
Fixing Bundled Linux FFMPEG commands

### LINKED ISSUE #1109: [BUG] Transcode error in desktop release
transcode_error_desktop

### PR DESCRIPTION
**Pull request by BryonLewis**
fixes #1109 

The bundling of ffmpeg between linux and windows is different.  The bundled FFMPEG for Windows will support libx264 and all the commands we are used to using (specifically `libx264` and `-crf`.  The Linux bundled version does not have support for these commands.

Initially there was a small typo in the linux transcoding `-c: a copy` was supposed to be `-c:a copy`. 

Once that was fixed I noticed that videos that required realignment while using the linux bundled VIAME weren't working properly and that was because we were passing in `libx264` and `-crf 18` into the relaginment command.

### CODE REVIEW

**Comment by BryonLewis** [comment]
This may change if a new VIAME release can get libx264 support built in for the Linux version.

**Comment by subdavis** [comment]
Should I go ahead and review or wait?

**Comment by BryonLewis** [comment]
> Should I go ahead and review or wait?

These bugs only affect users who have Linux VIAME and no ffmpeg on their path.  Windows users should be fine.  I think we can hold off as the code would be simplified if a new Linux VIAME build contains ffmpeg with the supported options.

**Comment by BryonLewis** [comment]
I just realized I can check the viame Install of ffmpeg to see if it contains `libx264` and change the versions if it doesn't.  So I'll add to the testing testing to see if the VIAME install has the proper capabilities.

**Comment by BryonLewis** [comment]
Closing because a new version VIAME was released that has support for libx264.

**Pull request closed without merging**
