### PR TITLE
ToolTip overflow Fix and positioning

### LINKED ISSUE #1051: [BUG] Fix Max width Tooltip display
**Describe the bug**
When using the tooltip hover fix the max-width for large names

**To Reproduce**
Load up data with long type names and turn on the tooltip hovering 

**Expected behavior**
Proper truncation or wrapping for the display area for the tooltip

### PR DESCRIPTION
**Pull request by BryonLewis**
fixes #1051 

- Fixes the tooltip text overflow issue by allowing it to take the full size required.
- Moves the tooltip to the most inside box upper right hand side
- Sorts the items in the tooltip for inside-out.

### CODE REVIEW

**Comment by subdavis** [comment]
# Question 1

What's so bad about tooltip that follows mouse?

https://user-images.githubusercontent.com/4214172/142263517-b81fe0ac-344c-47e7-acdd-1f0d1c77ccaf.mp4

# Question 2

Seems like this still isn't optimal.  You can end up completely covering a bounding box with a tooltip with no way around it.

https://user-images.githubusercontent.com/4214172/142263521-a44e0529-8df5-405a-ab0e-8edb80f3bac9.mp4

# Question 3

Also seems like there's a race condition somewhere.  The tooltip doesn't update sometimes when you move around.

https://user-images.githubusercontent.com/4214172/142263524-5492b214-bc57-4ba9-a33a-600cc580bb90.mp4

**Comment by BryonLewis** [comment]
> # Question 1
> What's so bad about tooltip that follows mouse? It seems pretty responsive to me.
> 
If your happy with the responsiveness we can go with that.  The only counterpoint is that we have had some complaints about the tooltip drawing icons and people not liking them following the mouse closely. Maybe instead of a hover based tool it requires a different action to trigger?
> # Question 2
> Seems like this still isn't optimal. You can end up completely covering a bounding box with a tooltip with no way around it.
Yeah, this is probably a problem given that it appears in the same location for the inside box each time so it will always hide outside box.
> # Question 3
> Also seems like there's a race condition somewhere. The tooltip doesn't update sometimes when you move around.
> 
I'm having trouble consistently replicating this but I did manage to get it to happen.  It seems to happen a bit more when zoomed in vs the entire image.

Thank you for the feedback and questions.  I'm leaning more towards just having it attached to the mouse now.

**Comment by subdavis** [comment]
With option 1 (follow pointer) I did notice that depending on zoom level, the tooltip can be under the pointer and intercept mouse interactions.  IDK if there's a reliable way around that.  Because the coordinates are in image-space and not screen-space, having a constant offset is probably undesirable.

**Comment by subdavis** [comment]
> If your happy with the responsiveness we can go with that. The only counterpoint is that we have had some complaints about the tooltip drawing icons and people not liking them following the mouse closely

As I recall, that was related to doing annotation.  Someone thought the icons were in the way while drawing, which is fair.  This you can turn off and isn't really useful while drawing anyway, so it's probably fine, but we should get someone like Matt or Roddy to actually decide.

**Comment by waxlamp** [comment]
> With option 1 (follow pointer) I did notice that depending on zoom level, the tooltip can be under the pointer and intercept mouse interactions. IDK if there's a reliable way around that. Because the coordinates are in image-space and not screen-space, having a constant offset is probably undesirable.

I also like Option 1. As for the image space / screen space issue, my gut tells me to ask David Manthey about it. GeoJS has ways to plot things in screen space, if I am not mistaken.

**Comment by subdavis** [comment]
This is perfect.  I couldn't figure out from the code how you got the padding in screen space though, just curious

**Comment by BryonLewis** [comment]
> This is perfect. I couldn't figure out from the code how you got the padding in screen space though, just curious

I just pushed the changes, I need to self review it.  I'm still using the `position` function provided geoJS but I looked at what it does internally inside of geoJS, converted to display corrdinates, added the offset and then converted back into the geojs coordinates used for the display.

The zooming event only supplies info in screenspace (relative to the element) so I would have to do some more conversions to get it right and that coordinate doesn't change after each zoom.  It was much easier to just save the last mousePosition and use it like a mouseMove function for the zooming instead.

**Review by subdavis — DISMISSED** [review]
Perfect.  I tested pretty extensively including annotation and continuous mode, editing, deleteing, etc, all looking great.

**Review by subdavis — APPROVED** [review]

**Pull request merged**
