### PR TITLE
FPS Clamping DIVE

### LINKED ISSUE #716: [BUG] Clamp downsample FPS to raw video framerate
**Describe the bug**
Don't allow workers to request downsample rate higher than video rate.

**To Reproduce**
1. Set FPS higher than video fps at upload
2. Run a pipe
4. See misalignmentg.s

**Related data**
https://viame.kitware.com/girder/#item/607f22d01d59f9054923620f

**Expected behavior**
During ffprobe, if discovered FPS is smaller, change the metadata.

### LINKED ISSUE #768: [FEATURE] Variable FPS loading for video annotation in desktop version
You seem to only be able to run 10 FPS pipes through web right now

### PR DESCRIPTION
**Pull request by subdavis**
fixes #716 
fixes #768

### CODE REVIEW

**Review by BryonLewis — CHANGES_REQUESTED** [review]
Besides the desktop version parseInt it seems to work as intended and clamps to the lowest.

I've also noticed another thing with bounce back video playing at the end occurring with non integer frame rates.  The video gets to the end of the file and I think our calculated time doesn't match the current time so it keeps swapping between the last two frames.

Then I noticed on this video (25fps and set the annotation to 25 fps) I got this back:
image

image

My mind doesn't want to focus right now on the nuances of annotation vs video frame rate so I'm unsure as to what is happening.

**Comment by BryonLewis** [comment]
Is this going to be implemented on desktop as well? (can be a different PR)

**Comment by subdavis** [comment]
It's already implemented on desktop, but there's no option to select FPS right now, so it only matters for FPS < 5.  I'm thinking about adding that to this PR

**Comment by BryonLewis** [comment]
Should this read CSV metadata from other runs and try to guess the annotation rate?

**Comment by subdavis** [comment]
It's not technically part of the open issue, but it should be done, so I might as well add it.

**Review by BryonLewis — CHANGES_REQUESTED** [review]
I think the only thing I found was the audio stream issue with ffprobe returned results.

**Review by BryonLewis — APPROVED** [review]
My testing included some malformed  fps metadata and other stuff and it seems to properly handle all of that now.  Did some testing using some run annotations at different frame rates and it all seems good.

**Pull request merged**
